variable "region" {}
variable "vpc_cidr" {}
variable "instance_tenancy" {}
variable "project_name" {}
variable "public_subnets_cidr" {}
variable "private_subnets_cidr" {}
variable "allocated_storage" {}
variable "storage_type" {}
variable "max_allocated_storage" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "username" {}
variable "password" {}
variable "parameter_group_name" {}
variable "repository_name" {}
variable "image_tag" {}
variable "cpu" {}
variable "memory" {}
variable "db_name" {}
